# Generated by Django 4.2.17 on 2024-12-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales_cursos/')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('ppt', 'PPT'), ('excel', 'Excel'), ('imagen', 'Imagen'), ('otro', 'Otro')], max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='core.curso')),
            ],
        ),
    ]
