# Generated by Django 5.1.3 on 2024-11-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_saga_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saga',
            options={'ordering': ['creado'], 'verbose_name': 'Saga', 'verbose_name_plural': 'Sagas'},
        ),
    ]
