# Generated by Django 5.1.2 on 2024-10-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResidentEvilItem',
            new_name='noticias',
        ),
    ]
