# Generated by Django 5.1.2 on 2024-10-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_residentevilitem_noticias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
