# Generated by Django 5.1.2 on 2024-10-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
