# Generated by Django 5.1.2 on 2024-10-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_alter_noticia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
